//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace realEstateDevelopment.MVVM.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeProjects
    {
        public int EmployeeID { get; set; }
        public int ProjectID { get; set; }
        public int Id { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Projects Projects { get; set; }
    }
}
