//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace realEstateDevelopment.MVVM.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoryOfChanges
    {
        public int IdOfChange { get; set; }
        public int EmployeeId { get; set; }
        public string Operation { get; set; }
        public System.DateTime DateAndTimeOfChange { get; set; }
    
        public virtual Employees Employees { get; set; }
    }
}
