//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace realEstateDevelopment.MVVM.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materials
    {
        public int MaterialID { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public string MaterialName { get; set; }
        public string Type { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
    
        public virtual Suppliers Suppliers { get; set; }
    }
}
