//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace realEstateDevelopment.MVVM.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rental
    {
        public int RentId { get; set; }
        public int ApartmentId { get; set; }
        public int ClientId { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime StartOfRental { get; set; }
        public Nullable<System.DateTime> EndOfRental { get; set; }
    
        public virtual Apartments Apartments { get; set; }
        public virtual Clients Clients { get; set; }
        public virtual Clients Clients1 { get; set; }
    }
}
