//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace realEstateDevelopment.MVVM.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Revenues
    {
        public int RevenueID { get; set; }
        public int ProjectID { get; set; }
        public string RevenueType { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime RevenueDate { get; set; }
    
        public virtual Projects Projects { get; set; }
    }
}
